service: stone

frameworkVersion: '2'

provider:
  name: aws
  endpointType: regional
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  environment:
    USER_TABLE_NAME: ${self:custom.UserTable.name}
  iamRoleStatements:
    - ${file(iam/UserTableIAM.yml):UserTableIAM}

resources:
  Resources:
    UserTable: ${file(resources/UserTable.yml):UserTable}

functions:
  incrementCounter:
    handler: src/handlers/incrementCounter/handler.handler
    events:
      - httpApi:
          path: /counter/{key}
          method: post

  getCounter:
    handler: src/handlers/getCounter/handler.handler
    events:
      - httpApi:
          path: /counter/{key}
          method: get

  createUser:
    handler: src/handlers/createUser/handler.handler
    events:
      - httpApi:
          path: /user
          method: post

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

  UserTable:
    name: !Ref UserTable
    arn: !GetAtt UserTable.Arn

plugins:
  - serverless-offline